<?php
/**
 * Address
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.19
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Address model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class Address 
{
        /**
     * @var string|null
     * @SerializedName("street")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $street = null;

    /**
     * @var string|null
     * @SerializedName("city")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $city = null;

    /**
     * @var string|null
     * @SerializedName("state")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $state = null;

    /**
     * @var string|null
     * @SerializedName("zip")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $zip = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->street = array_key_exists('street', $data) ? $data['street'] : $this->street;
            $this->city = array_key_exists('city', $data) ? $data['city'] : $this->city;
            $this->state = array_key_exists('state', $data) ? $data['state'] : $this->state;
            $this->zip = array_key_exists('zip', $data) ? $data['zip'] : $this->zip;
        }
    }

    /**
     * Gets street.
     *
     * @return string|null
     */
    public function getStreet(): ?string
    {
        return $this->street;
    }

    /**
    * Sets street.
    *
    * @param string|null $street
    *
    * @return $this
    */
    public function setStreet(?string $street = null): self
    {
        $this->street = $street;

        return $this;
    }




    /**
     * Gets city.
     *
     * @return string|null
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
    * Sets city.
    *
    * @param string|null $city
    *
    * @return $this
    */
    public function setCity(?string $city = null): self
    {
        $this->city = $city;

        return $this;
    }




    /**
     * Gets state.
     *
     * @return string|null
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
    * Sets state.
    *
    * @param string|null $state
    *
    * @return $this
    */
    public function setState(?string $state = null): self
    {
        $this->state = $state;

        return $this;
    }




    /**
     * Gets zip.
     *
     * @return string|null
     */
    public function getZip(): ?string
    {
        return $this->zip;
    }

    /**
    * Sets zip.
    *
    * @param string|null $zip
    *
    * @return $this
    */
    public function setZip(?string $zip = null): self
    {
        $this->zip = $zip;

        return $this;
    }



}


